### ISSUE TITLE
router + switch

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-shopping-list-template#6]
I merged your pull request but this issue is not solved.

I'm not run your project on local PC, but i'm pretty sure that it'll generate an error, because Switch should be wrapped by Router - Main Component
More at:
https://medium.com/@pshrmn/a-simple-react-router-v4-tutorial-7f23ff27adf
https://reacttraining.com/react-router/core/guides/philosophy

**Comment by AminuSufi585** [comment]
Hi @atherdon,

Since the time you label that bug, I keep looking for a fix. And what was so confusing to me is that there is no single error in my developer console. I went ahead to install React Dev tools but to no avail.

However, I finally learned that the code I wrote is just as you suggest it should be. 
- First I wrap the **App** component inside **BrowserRouter** (imported from react-router) in **index.js**
- Then I wrap the **Header** and **Main** components inside **App** component in **App.js**
- Inside **Header**, I set up a simple navigation using **Link** (imported from react-router) in **Header.js**
- Inside **Main**, I set up the switching with all the respective **Route** components inside **Switch** in **Main.js**
- Ultimately, **Switch** was wrapped in **BrowserRouter**

Thanks a lot for the links above, it helps me in reinforcing what I had learned.
